# Generated by Django 3.0.8 on 2020-08-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizGame', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteModel',
        ),
    ]
